[project]
name = "nebulagraph-lite"
version = "0.0.8"
description = "Plug and play NebulaGraph with pip install."
authors = [
    {name = "Wey Gu",email = "weyl.gu@gmail.com"},
]
dependencies = [
    "udocker>=1.3.12",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "Apache 2.0"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
package-type = "library"
