name: PR Workflow
on:
  pull_request:
    branches:
      - main

jobs:
  build-and-lint-test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: pdm-project/setup-pdm@v3
      with:
        python-version: '3.x'
        cache: true
    - name: Install dependencies
      run: pdm install

    - name: Lint
      run: pdm run lint

    - name: Build and Install NebulaGraph-Lite
      run: pip3 install .
    
    - name: Dry run `nebulagraph start`
      run: nebulagraph --debug start --cleanup

  end-to-end-test-bare-metal:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, centos-7, rocky-linux-8, ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run Build and Install
      run: |
        echo "Running tests on ${{ matrix.os }}"
        pip3 install .
    - name: Dry run `nebulagraph start`
      run: nebulagraph --debug start --cleanup

  end-to-end-test-docker:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        image: ["ubuntu:20.04", "centos:7", "rockylinux:9", "ubuntu:latest"]
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        if grep -qEi "debian|buntu" /etc/*release; then
          apt-get update && apt-get install python3-pip curl which -y
        else
          yum update -y && yum install python3-pip which -y
        fi
    - name: Install NebulaGraph-Lite
      run: pip3 install --user .
    - name: Run NebulaGraph-Lite in container
      run: nebulagraph --debug --container start
