name: Build Checks

on:
  release:
    types:
      - published

jobs:

  build-lint-and-test:
    uses: ./.github/workflows/pr.yaml

  release-and-publish:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - uses: pdm-project/setup-pdm@v3
      with:
        python-version: '3.x'
        cache: true

    - name: Install dependencies
      run: pdm install

    - name: Build and publish
      env:
        PDM_PUBLISH_USERNAME: ${{ secrets.PYPI_NAME }}
        PDM_PUBLISH_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: pdm publish
